spring:
  rabbitmq:
    addresses: xxx
  cloud:
    stream:
      bindings:
        output:
          destination: mail
          group: mail-group
client:
  service:
    url:
      ms-alarm: ${CLIENT_SERVICE_URL_MS-ALARM}
      ms-article: ${CLIENT_SERVICE_URL_MS-ARTICLE}
      ms-auth: ${CLIENT_SERVICE_URL_MS-AUTH}
      ms-complaint: ${CLIENT_SERVICE_URL_MS-COMPLAINT}
      ms-mail: ${CLIENT_SERVICE_URL_MS-MAIL}
      ms-subscriber: ${CLIENT_SERVICE_URL_MS-SUBSCRIBER}
      ms-team: ${CLIENT_SERVICE_URL_MS-TEAM}
